<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="5" hostname="ip-172-31-22-110" name="com.simplilearn.MyTestClass2" tests="6" failures="1" timestamp="2021-10-23T07:28:09 UTC" time="0.002" errors="0">
  <testcase name="test2_3" time="0.000" classname="com.simplilearn.MyTestClass2">
    <skipped/>
  </testcase> <!-- test2_3 -->
  <system-out/>
  <testcase name="test2_4" time="0.000" classname="com.simplilearn.MyTestClass2">
    <skipped/>
  </testcase> <!-- test2_4 -->
  <system-out/>
  <testcase name="beftest" time="0.002" classname="com.simplilearn.MyTestClass2">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at com.simplilearn.MyTestClass2.beftest(MyTestClass2.java:39)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:62)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:385)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:321)
at org.testng.TestRunner.invokeTestConfigurations(TestRunner.java:637)
at org.testng.TestRunner.beforeRun(TestRunner.java:627)
at org.testng.TestRunner.run(TestRunner.java:589)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- beftest -->
  <system-out/>
  <testcase name="test2_1" time="0.000" classname="com.simplilearn.MyTestClass2">
    <skipped/>
  </testcase> <!-- test2_1 -->
  <system-out/>
  <testcase name="test2_2" time="0.000" classname="com.simplilearn.MyTestClass2">
    <skipped/>
  </testcase> <!-- test2_2 -->
  <system-out/>
  <testcase name="test2_5" time="0.000" classname="com.simplilearn.MyTestClass2">
    <skipped/>
  </testcase> <!-- test2_5 -->
  <system-out/>
</testsuite> <!-- com.simplilearn.MyTestClass2 -->
